### ISSUE TITLE
Parse error in presence of accent

### ISSUE THREAD

**Issue by cristianolongo** [nexacenter/public-contracts#23]
Putting "Università degli studi di Catania" in the main form I got the following error:

<pre>
Error: parser error: Error: Syntax error: unexpected "Virtuoso" on line 1..
</pre>

**Comment by alemela** [comment]
@cristianolongo The page exists and is http://public-contracts.nexacenter.org/view/02772010878

The problem is that you have to interact with the search form to obtain the right page. For example writing the string instead to copy and paste. This is also correlated with #10.

Idea for a better behaviour?

**Comment by nicorusti** [comment]
IN this case the problem is that this university seems to have 6billion+ euros of tenders, they have some severe mistake in the xml files

**Comment by alemela** [comment]
@nicorusti yes, probably the numbers are wrong due to some xml error. However the topic of this issue is the strange form search's behavior.

**Comment by nicorusti** [comment]
Off topic: the xml contains wrong figures 
      <importoAggiudicazione>6182230969.00</importoAggiudicazione>

**Comment by giuseppefutia** [comment]
The issue with "Università degli studi di Catania" is due to the main label associated to this entity, that in this case is "Universita degli Studi di Catania" (without accent). If you type the latter (or you use the link suggested by @alemela ), you will find the information.

The issue is obviously wider: we are looking for a method/official repository to associate the correct label to companies and public administrations.

**Comment by alemela** [comment]
What said @giuseppefutia is true but I think is not complete explanation for this problem. Because also if you put "Universita degli Studi di Catania" obtain the same error. The only string that you can copy and paste in the search form is "UNIVERSITA DEGLI STUDI DI CATANIA" but also in this case, you can't press "Go!" but you have to select the hover suggestion. This is quite wired, indeed.

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#10
