### ISSUE TITLE
Choose the right label for business entities

### ISSUE THREAD

**Issue by giuseppefutia** [nexacenter/public-contracts#3]
Business entities have bad labels due to incorrect data published in the XML files. How we fix them?

**Comment by alemela** [comment]
IMHO there are mainly 2 ways:
* using an authoritative dataset to create for each vatID a "super" label that we know being valid
    * pro: simple and we centralize the process to only a subset of auth dataset
    * cons: we don't have auth dataset and they could also be full of errors
* writing a "smart" text recognition algorithm that find the most recurrent pattern from the labels' set
    * pro: no other data need and can scale
    * cons: it doesn't resolve all the problems (i.e. those entity with just one valid label and other completely different) and can returns wrong results

**Comment by nicorusti** [comment]
Im

**Comment by nicorusti** [comment]
I'm working on second solution!

**Comment by giuseppefutia** [comment]
Adding a link to each business entity could be temporary solution for the disambiguation: https://github.com/giuseppefutia/vis-public-contracts/issues/6

**Comment by giuseppefutia** [comment]
We have improved the quality of labels through a text recognition algorithm and we have added a link to each business entity for the disambiguation.

**Comment by traversaro** [comment]
Regarding the first solution that was proposed.. there are several interesting datasets regarding business entities related with public bodies: 

* The ANAC Casellario delle Imprese (http://casellario.avcp.it) is a database of ~70K companies that are registered for partecipate in several kind of tenders. The data is not free, but in the past I wrote a scraper (https://classic.scraperwiki.com/scrapers/casellario_imprese_avcp/) that currently is inactive because Classic ScraperWiki is no longer working but can be reactivated if it can be useful. 

* The "Casellario società di ingegneria e professionali" ( http://socing.avcp.it/ ) is a register of the companies of engineering professional services. The data is not open and not easy to scrape in bulk, but an easy url can be accessed given the fiscal number of the company (see for example: http://socing.avcp.it/anagrafica.php?CodiceFiscale=06393070484 ). Hence it would be easy to get all the data related to a list of fiscal number, as the one that can be extracted from `public-contracts`. 

There are several other sources that may be interesting.. but for sure this two are the one that are easier to use.

**Comment by giuseppefutia** [comment]
Thank you for you suggestions, @traversaro!

**Comment by Tonyz1** [comment]
@traversaro can you upgrade the scraper for avcp to the new site morph.io that I want to "play" with this?

**Comment by Tonyz1** [comment]
@traversaro can you do the upgrade of the scraper to the new site so I play with it a bit. Thanks
